version: '3'

services:
    presenter:
        build: .
        container_name: presenter
        command: gunicorn --bind unix:/run/bitchart/gunicorn.sock app:app
        volumes:
            - "./run:/run/bitchart"  # for gunicorn.sock
            - "./var:/var/log/bitchart"
            - ".:/opt/bitchart"

    analyzer:
        build: .
        container_name: analyzer
        command: python analyze.py
        volumes:
            - "./var:/var/log/bitchart"
            - ".:/opt/bitchart"

    watcher:
        build: .
        container_name: watcher
        command: python watch.py
        volumes:
            - "./var:/var/log/bitchart"
            - ".:/opt/bitchart"

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - "./nginx/bitchart.conf:/etc/nginx/conf.d/default.conf"
            - "./run:/run/bitchart"
